sudo: required
services:
- docker
branches:
  only:
  - master
  - develop
script:
- export ENV_FILE=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "prod"; else echo
  "stage"; fi`
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ];  then echo "production"; elif [
  "$TRAVIS_BRANCH" == "develop" ]; then echo "stage"; else echo "dev-$(git rev-parse
  --short HEAD)"; fi`
- docker build --no-cache -t jincort/quantor-frontend-ico-dashboard-develop:${TAG} .
- docker run --rm -v $(pwd):/usr/src/app jincort/quantor-frontend-ico-dashboard-develop:${TAG}
  /bin/sh -c "yarn && cp -r .env.${ENV_FILE} .env && yarn build && yarn run lint:all"
after_success:
- export DOCKERFILE=`if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "Dockerfile.stage";
  else echo "Dockerfile.prod" ; fi`
- docker build -f $DOCKERFILE --no-cache -t jincort/quantor-frontend-ico-dashboard:${TAG}
  .
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push jincort/quantor-frontend-ico-dashboard-develop:${TAG}
- docker push jincort/quantor-frontend-ico-dashboard:${TAG}
notifications:
  slack:
    secure: ZRdhxdwpsHgXafGExFO51k2HhB9YAJLA2TG+/mcqJmqqRaizWJypPukBaqO+rp+G5rBbSg5wyABf2p6WlEzruBFghUwL6SVbb+ZAmvxOm1TDM6DdHcFLWSTREzvDaUYoADAwLO4vq/2I76B8dlhlbZN2ElJjGszRCUKSazjzmtToQxVZsy4iZVUfnb5x/6wE5T3vr5d950N4sSQrk/uqBG0v3QXJ9RJ0yLb+WJpJS1zjlSg4ojLV+qj7RQyLmoWotlF8L7B0PdxbSJfjuesyRlhB4nBgQFqKNTApjT7BcmaDVnU5JWsyJ41SovFO67hHMal2e7aK22Q8j9zjpC1w841tBG5kkRRS1mENUvpp1u65Ah18QMLcsb7M9H3IBH7AgvsvLFMn6zgptlDPezhRyJyMQy83GbfNl0PxSeIBEtO9hxyHCO3YzLPaDkwWljB6plUKSoN+6a3VR9k1sPQWdC69xus5skLQuK61hwS8yuTLobSBupL1Bw7j+0UqMbBGGvEalZ15QnfLFPlvbk7tG+1KexqIqDIivzX9XVpKxmOk68PfZ+mSDwQ0sivpZAUqjmRnk8f16W19eytGsm/fTEEN3x6KCdfEbKO+yGJXOxXAvi8xXmQ8HjQ4Q2Li5kdSIZn9G4dACMzdOqnZdvzH1lB7XNXOPFiXDoVm5zL09vU=
env:
  global:
  - secure: eWOQ9xQpj+mLnK5WIDnbT/G3nsEiscbcFx15KixT6sd5oUfczmardL//HKJz78JTPg0Kqh1boyLZRL/1W1E/1uXhC2d1dgHtJGCCHqgELBGQdxc1U66gMGt544xsvzzjzMT0skCNUGgYQ6bdrdRhj3oiLNfzdyHbpxsvwBHjvhIh2Esksnu5QWjtRrj9DHj6em36l0Bfx6PnqkncOygglD7l2c/oUzsVcgfT/g/YpGA07/k3G+KU7ayX2QvevMj8MGgDPeM6Lepep+IhMZhHcqMs2oaVoCiLGnhPUEbFlCqSUwokjgwPuiiAlXygTpXQflXMHJKct77J4OamsfkBm4ngG2Qni9H8LeN7CaAsZYYOfoxAZx6pzojEIn56iIcUFl+5fl7ppWO9PAn0CLfBpNIFN8E3Vc4XF8zjpmc2qNEQawBWq43qTgPsLtQhfvlBuL2kmKFSx7Gc7jfyaZHzbrYiQjDr7JkN8pG0bjPCw3Ui77xQrk0MZ/TXicsDe3Dw0cNzmhlEskCb+S/T+3xlZi9I5zfdoN7a5qoviA2TblUBWuJ4yT/hCD6FuU5newszrj2MQx6vHAH8FTLzLm4EvEl0A+WAkW5hnXxq3CJpeENx2JPgoVtRgMKs7rWsL3sW6Q40jVRScEtHRVA7TQ5qztgvnrojg1Kt568Fu2G3pCI=
  - secure: CF07cbKveUgEuWzOuca/yzL107LulxwMSEoc7qg1X7APXfVQFt8/aUtQslw+iFFag4XSwTPYZxErYIwKgv+T8KBBJ4gwOZ/dSypyL79czaqcvSV/2mH+t3LOvTysdmQVZ0H2DWQifIq3m9IBMz/SjyrCgnA9uiMW83juZPqQFaT4VmGJ1kEdfVXt1JfClykMbDNm8mlJrvcgeDHSf8Cz5VpbIWjn5x4uaAxF36zGWmB7lM8Gpg8mg4qwfTU2kmUskNGfBBDBXbUjamDwZtN7fI1vHHLzdVeaFVE9OGFREHvvnsF3kHMo2sTAOHESJg6+VnT6GOsZmDtiwyj+ph3mFVcho+7XY/eQNfy9WJ5GveXYZ7aYTkJ2874BhEEYwhW+Kw79xZcYwFAIdUAE30nNg/543oxnytJ4EZIEQ1DqIvCF2ackjWvzmv+XO/VfSQQbZ5oSYD2xakrMLP+fpS+2ya/LYHPgXkiQTjQozGcMWCNIRvxK/ZuYT17gh6t5j2qvJGA9gQjB7DW2EsJwaqL+yo/iJNAKK88NN1rNBL+ew/5kkz1k3CZ5umINrEK1VXuClzXYvdvmV/DlXcTWxsXqwQhaTSZ91/wN+TZZwYzwyrIDOxi1kOSJTmdwWMqJApwrDq8kydRAxaP3m8Lido8c4Gz3jqKcimPpHMXRacq5Jv8=
